---
- name: getting state list
  uri:
    url: https://cdn-api.co-vin.in/api/v2/admin/location/states
    method: GET
    status_code: 200 
  register: state_details
  tags: state_list 
- name: printing state list
  debug: 
    msg: '{{ state_details }}'
  tags: state_list
- name: getting specific list
  uri:
    url: https://cdn-api.co-vin.in/api/v2/admin/location/districts/{{ state_id }}
    method: GET
    status_code: 200 
  register: specific_state_details
  tag: state_specific
- name: printing specific_state list
  debug: 
    msg: '{{ specific_state_details }}'
  tags: state_specific