---
- name: getting state list
  block:
  - name: getting state list
    uri:
      url: https://cdn-api.co-vin.in/api/v2/admin/location/states
      method: GET
      status_code: 200 
    register: state_details
    tags: state_list 
  - name: printing state list
    debug: 
      msg: '{{ state_details }}'
    tags: state_list
  rescue:
  - name: printing error msg
    debug:
      msg: "error in getting state list"
    tags: state_list 
- name: getting specific list
  uri:
    url: https://cdn-api.co-vin.in/api/v2/admin/location/districts/{{ state_id }}
    method: GET
    status_code: 200 
  register: specific_state_details
  when: state_details.status == 401
  tags: state_list 
- name: printing specific_state list
  debug: 
    msg: '{{ specific_state_details }}'
  tags: state_list 
  when: state_details.status == 401
  # failed_when: state_details.status == 401