---
- name: commond module
  hosts: localhost
  become: yes
  tasks:
  - name: checking what is inside the directory
    command: 
      cmd: ls
      chdir: /home/ec2-user/ansible-code
    register: output
  - name: printing output
    debug:
      msg: "{{ output }}"
