---
- name: copy module
  hosts: localhost
  tasks:
  - name: copy file with owner and persmissions
    ansible.builtin.servce:
      src:
      dest:
      owner:
      group:
      mode:
    register: copied_file
  - name: printing destination copied file
    debug:
      msg: "{{ copied_file }}"

