---
- name: copy module
  hosts: localhost
  become: yes
  tasks:
  - name: copy file with owner and persmissions
    copy:
      src: /home/ec2-user/ansible-code/user.txt
      dest: /home/ec2-user/ansible-code/cowin/user.txt
    register: copied_file
  - name: printing the output of destination file 
    debug:
      msg: "{{ copied_file }}"

