---
- name: file module
  hosts: localhost
  become: yes
  tasks:
  - name: changing permission to script1.sh
    file:
      path: /home/ec2-user/ansible-code/script1.sh
      mode: '777'
    register: output
    tags: first
  - name: printing output
    debug:
      msg: "{{ output }}"
    tags: first
  - name: changing permission to script3.sh
    file:
      path: /home/ec2-user/ansible-code/script3.sh
      mode: '777'
    register: second_output
    tags: second
  - name: printing second output
    debug:
      msg: "{{ second_output }}"
    tags: second
  - name: touch a file if not existed
    file:
      path: /home/ec2-user/ansible-code/modules/directorymodule.yml
      state: touch
      mode: '777'
    register: third_output
    tags: third
  - name: printing third output
    debug:
      msg: "{{ third_output }}"
    tags: third
  - name: create a directory
    file:
      path: /home/ec2-user/ansible-code/newdirectory
      state: directory
      mode: '0755'
    register: fourth_output
    tags: fourth
  - name: printing the fourth_output
    debug:
      msg: "{{ fourth_output }}"
    tags: fourth
  - name: delete the new the directory
    file:
      path: /home/ec2-user/ansible-code/newdirectory
      state: absent
    register: fifth_output
    tags: fifth
  - name: printing the fifth_output
    debug:
      msg: "{{ fifth_output }}"
    tags: fifth