---
- name: service module
  hosts: localhost
  tasks:
  - name: start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
    register: httpd_service
  - name: printing output of httpd service
    debug:
      msg: "{{ httpd_service }}" 
  - name: stop service httpd, if started
    ansible.builtin.service:
      name: httpd
      state: stopped
    register: httpd_service_stop
  - name: printing output of httpd stop service
    debug:
      msg: "{{ httpd_service_stop }}"