---
- name: creating new employee record
  block:
  - name: creat new employee record
    uri:
      url: http://dummy.restapiexample.com/api/v1/create
      validate_certs: no
      method: "POST"
      body_format: json
      body:
        {
          "name": "{{name}}", 
          "age": "{{age}}",
          "salary": "{{salary}}"
        }
    register: crete_new_record
    tags: newrecord
  - debug:
      msg: "{{crete_new_record}}"
    tags: newrecord
    when: crete_new_record.status == 200
  rescue: 
  - name: printing error message
    debug:
      msg: "error in printing message"
    tags: newrecord
  # failed_when: crete_new_record.status == 200