---
- name: update employee record
  uri:
    url: http://dummy.restapiexample.com/api/v1/update/{{idnumber}}
    method: PUT
    body_format: json
    body: 
      {
        "employee_name": "{{employee_name}}",
        "employee_salary": "{{ employee_salary }}",
        "employee_age": "{{ employee_age }}"
      }
    status_code: 200
    return_content: yes
    # content_type: application/json
  register: updated_record
  tags: update_employee_record 
- debug:
    msg: "{{ updated_record }}"
  tags: update_employee_record   

