---
- name: getting availability list
  uri:
    url: 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode={{ pincode }}&date={{ date }}'
    method: GET
    status_code: 200 
  register: availability_details
  tags: availability
- name: printing availability_details
  debug: 
    msg: '{{ availability_details }}'
  tags: availability
  notify:
    - Restart memcached
    - Restart apache 