---
- name: generate OTP
  uri:
    url: https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP
    validate_certs: no
    method: "POST"
    body_format: json
    body:
      {
        "mobile": "{{mobile_number}}"
      }
  register: OTP_details
  tags: generate_otp
- debug:
    msg: "{{OTP_details}}"