---
- name: Dummy APIs
  hosts: localhost
  tasks:
- name: pulling all employees information
  uri:
    url: https://reqres.in/api/users?page=2
    method: GET
    status_code: 200
  register: employee_information
- name: printing employee information 
  debug:
    msg: '{{ employee_information }}'
