---
- name: test
  hosts: localhost
  connection: local
  vars:
    username: arun
    hostname: ['host1','host2','host3','host7','host9']
  tasks:
  - name: print password
    user:
      username: "{{ username }}"
    register: test
  - debug:
      msg: "{{ test }}"
  - name: print password
    hostname:
      hostname: "{{ hostname }}"
    register: test1
  - debug:
      msg: "{{ test1 }}"

      # host1..host2....host3.. host7...host9
      # host1_3-7-9
  
